### ISSUE TITLE
Hero image blocks Nav bar components on small screens

### ISSUE THREAD

**Issue by meli-imelda** [traleor/templates#1]
@NjohPrince, @itzomen   On the bellissima template on trying to make the Nav bar responsive, I have this issue.
The Nav bar is responsive indeed but I can't seem to get the Hero image to be placed behind the Nav bar.

**Comment by itzomen** [comment]
Ok, I will look into it later today 

Yup I see what you mean. [View demo](https://traleor.github.io/templates/bellissima/)

**Comment by NjohPrince** [comment]
Ohh ok, sorry just coming online

**Comment by itzomen** [comment]
@NjohPrince @meli-imelda I could not figure out why the navbar is covered by the banner section but I found a workaround 

```css
 /* ************** Add this to banner when navbar expands on mobile ************/
.banner{
    visibility: hidden;
}
```
The problem now is I can't figure out how to add this to the banner when the menu input is checked e.g

```css
/* When menu checked */
  .navbar input:checked ~ .responsive__nav{
    top: 0;
  }
  .navbar input:checked ~ label .hamburger__menu {
    transform: translateX(-50px);
    background: transparent;
  }
  .navbar input:checked ~ label .hamburger__menu::before {
    transform: rotate(45deg) translate(35px, -35px);
  }
  
  .navbar input:checked ~ label .hamburger__menu::after {
    transform: rotate(-45deg) translate(35px, 35px);
  }
```
